1. Verify that your ansible installation is available by displaying the version of ansible while logged in as the 'user' user.
[test@tcox3 ~]$ ansible --version
ansible 1.9.2
  configured module search path = None
 
2. Run the ansible command that lists all of the hosts configured in your control server 'hosts' file for the system.
[test@tcox3 ~]$ ansible all --list-hosts
    tcox5.mylabserver.com
    localhost
    tcox4.mylabserver.com
 
3. Create a playbook, using the 'ingl' module that accomplishes the following:
- Uses SSH
- Logs in to the remote system as 'test' user
- Connects to all the hosts from Step #2 above
- The playbook runs as 'sudo'
- Skip gathering remote facts
- Runs a ping module against all hosts in the environment
[test@tcox3 Playbooks]$ vim ping.yml
[test@tcox3 Playbooks]$ cat ping.yml
--- # PING MODULE EXAMPLE
- hosts: all
  user: test
  connection: ssh
  gather_facts: no
  tasks:
    - name: Ping all the hosts
      ping:
 
4. Run the playbook and display the results.
[test@tcox3 Playbooks]$ ansible-playbook ping.yml
 
PLAY [all] ********************************************************************
 
TASK: [Ping all the hosts] ****************************************************
ok: [localhost]
ok: [tcox4.mylabserver.com]
ok: [tcox5.mylabserver.com]
ok: [tcox1.mylabserver.com]
 
PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
tcox1.mylabserver.com      : ok=1    changed=0    unreachable=0    failed=0
tcox4.mylabserver.com      : ok=1    changed=0    unreachable=0    failed=0
tcox5.mylabserver.com      : ok=1    changed=0    unreachable=0    failed=0