1. Verify that your ansible installation is available by displaying the version of ansible while logged in as the 'user' user.
[test@tcox3 ~]$ ansible --version
ansible 1.9.2
  configured module search path = None
 
2. Run the ansible command that lists all of the hosts configured in your control server 'hosts' file for the system.
[test@tcox3 ~]$ ansible all --list-hosts
    tcox5.mylabserver.com
    localhost
    tcox4.mylabserver.com
3. Create a tar/gz file containing whatever content you want and name it test.tar.gz in the /home/test directory on your control server.
4. Create a playbook, using the 'unarchive' module that accomplishes the following:
- Uses SSH
- Logs in to the remote system as 'test' user
- Connects to all the hosts from Step #2 above
- The playbook runs as 'sudo'
- Skip gathering remote facts
- Copy and then expand the file from the control server to the remote server from Step #2 above
[test@tcox3 Playbooks]$ vim unarchive.yml 
[test@tcox3 Playbooks]$ cat unarchive.yml 
--- # UNARCHIVE MODULE EXAMPLE
- hosts: aptserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: copy and unarchive a file
      unarchive: src=/home/test/local/test.tar.gz dest=/home/test/local copy=yes
5. Run the playbook and display the results.
[test@tcox3 Playbooks]$ ansible-playbook unarchive.yml 

PLAY [aptserver] ************************************************************** 

TASK: [copy and unarchive a file] ********************************************* 
ok: [tcox1.mylabserver.com]

PLAY RECAP ******************************************************************** 
tcox1.mylabserver.com      : ok=1    changed=1    unreachable=0    failed=0