Instructions
Your company has been increasing the deployment of small broacher-style websites for clients. The head of IT has decided that each client should have their own web servers for better client isolation and has tasked you with creating concept automation to quickly deploy web-nodes with simple static website content.
You have been provided an ansible control node and 2 test lab servers (node1 and node2) that have been preconfigured with the ansible user and key.
You must create an ansible inventory in /home/ansible/inventory containing a host group named web. The web group should contain node1 and node2.
Furthermore, you must design an Ansible playbook that will execute the following tasks on your configured inventory: install httpd, start and enable the httpd service, and install a simple website provided on a repo server. Create the playbook in /home/ansible/web.yml. The simple website may be accessed from http://repo.example.com/website.tgz.
Summary tasks list:
Create an inventory in /home/ansible/inventory containing a host group named web. The web group should contain node1 and node2.
Create a playbook in /home/ansible/web.yml.
Configure the playbook to install httpd on the web group.
Configure the playbook to start and enable the httpd service on the web group.
Configure the playbook to retrieve the website from http://repo.example.com/website.tgz on each server in the web group.
Configure the playbook to unarchive the website into /var/www/html on all servers in the web group.
Execute the playbook you created using the inventory you created to verify your work.
Important notes: 
For your convenience, Ansible has been installed on the control node.
The user ansible is present on all servers with appropriate shared keys for access to managed servers from the control node.
The ansible user has the same password as cloud_user.
/etc/hosts entries have been made on control1 for the managed servers.
Objectives
help
Create an inventory in */home/ansible/inventory* containing a host group named *web*. The *web* group should contain node1 and node2.
echo "[web]" >> /home/ansible/inventory
echo "node1" >> /home/ansible/inventory
echo "node2" >> /home/ansible/inventory
help
Create a playbook in */home/ansible/web.yml*.
echo "---" >> /home/ansible/web.yml
help
Configure the playbook to install *httpd* on the *web* group
Using a text editor, such as vim, edit /home/ansible/web.yml to contain the following text block below the line containing "---":
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum: name=httpd state=latest
help
Configure the playbook to start and enable the *httpd* service on the *web* group
Using a text editor such as vim, edit /home/ansible/web.yml to contain the following task block after the "install httpd task":
    - name: start and enable httpd
      service: name=httpd state=started enabled=yes
help
Configure the playbook to retrieve the website from *http://repo.example.com/website.tgz* on each server in the web group.
Using a text editor such as vim, edit /home/ansible/web.yml to contain the following task block after the "start and enable httpd" task:
    - name: retrieve website from repo
      get_url: url=http://repo.example.com/website.tgz dest=/tmp/website.tgz
help
Configure the playbook to unarchive the website into */var/www/html* on all servers in the web group.
Using a text editor such as vim, edit /home/ansible/web.yml to contain the following task block after the "retrieve website from repo" task:
    - name: install website
      unarchive: remote_src=yes src=/tmp/website.tgz dest=/var/www/html/
help
Execute the playbook you created using the inventory you created to verify your work.
ansible-playbook -i /home/ansible/inventory /home/ansible/web.yml