--- # NFS SERVER PLAYBOOK
- hosts: frijke2c.mylabserver.com
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfslibs_pkg: nfs-utils-lib
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmapr_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share
  tasks:
  - name: Install the NFS Server and Utilities
    yum: pkg=nfs-utils state=latest
  - name: Install the NFS Server Libraries
    yum: pkg=nfs-utils-lib state=latest
  - name: Copy the export file to remote server
    copy: src=files/exports.template dest=/etc/exports owner=root group=root mod                                                                                                                                                             e=644
  - name: Start the RPC bind Service
    service: name=rpcbind state=started
  - name: Start the NFS Service
    service: name=nfs-server state=started
  - name: Start the File Lock service
    service: name=nfs-lock
  - name: Start the NFS map service
    service: name=nfs-idmap state=started
  - name: Install the NFS client and Utilities
    yum: pkg=nfs-utils state=latest
    delegate_to: 127.0.0.1
  - name: Install the NFS Client Libraries
    yum: pkg=nfs-utils-lib state=latest
    delegate_to: 127.0.0.1
  - name: Start the RPC Client bind Service
    service: name=rpcbind state=started
    delegate_to: 127.0.0.1
  - name: Start the Client File Lock service
    service: name=nfs-lock
    delegate_to: 127.0.0.1
  - name: Start the Client NFS map service
    service: name=nfs-idmap state=started
    delegate_to: 127.0.0.1
  - name: Create Client Mount Directory
    file: path=/mnt/remote state=directory mode=755
    delegate_to: 127.0.0.1
  - name: Mount the filesstem on the Client from the NFS Server
    mount: name=/mnt/remote src=/var/share fstype=nfs state=present
    register: result
    delegate_to: 127.0.0.1
  - name: Show the client mount result
    debug: var=result
