--- # At module
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install the AT module
      action: yum name=at state=latest
    - name: Example of future command with AT module
     # at: command="ls -al /var/log > /home/test/at.log" count=1 units="minutes"
      at: command="ls -al /var/log >  /home/test/at.log" state=absent
