   #Playbook demo of debug and register statements
- hosts: RedHats7
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing telnet package
    yum:
      name: telnet
      state: latest
    register: reult
  - debug: var=result
