--- # My First YAML Playbook for Ansible
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Install Which Package?
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: restart HTTPD
    - name: Install ansible
      action: yum name={{ pkg_name }} state=installed
  handlers: 
    - name: restart HTTPD
      action: service name=httpd state=restarted

