--- # Script module
- hosts: local
  user: ansible
  connection: ssh
  sudo: yes
  gather_facts: no
  tasks:
  - script: /home/test/system_uptime.sh creates=/home/test/uptime.log creates=/home/test/uptime.log creates=/home/test/uptime.log 
