--- # Tag Functionality example
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet and tree packages
      yum: pkg={{ item }} state=latest
      with_items: 
        - telnet
        - tree
      tags:
        - packages
    - name: Verify telnet was installed
      raw: yum list installed | grep telnet > /home/ansible/pkg.log
      tags: 
        - verification
