--- # Wait for module example
- hosts: all
  user: ansible
  sudo: yes
  tasks:
    - name: Installing Apache Tomcat
      action: yum name=tomcat state=latest
    - name: waiting for Port 8080 to listen
      wait_for:
        port: 8080
        state: started
    - name: Verifying installation
      action: yum name=tree state=present
